-- AlterEnum
ALTER TYPE "AIGenerationType" ADD VALUE 'EXCERPT';
ALTER TYPE "AIGenerationType" ADD VALUE 'TAGS';
ALTER TYPE "AIGenerationType" ADD VALUE 'IMPROVE';
ALTER TYPE "AIGenerationType" ADD VALUE 'EXPAND';
ALTER TYPE "AIGenerationType" ADD VALUE 'SHORTEN';
ALTER TYPE "AIGenerationType" ADD VALUE 'CONTINUE';
ALTER TYPE "AIGenerationType" ADD VALUE 'SUMMARIZE';
ALTER TYPE "AIGenerationType" ADD VALUE 'FAQ';
ALTER TYPE "AIGenerationType" ADD VALUE 'SOCIAL';
ALTER TYPE "AIGenerationType" ADD VALUE 'SUGGESTIONS';
ALTER TYPE "AIGenerationType" ADD VALUE 'APPLY_SUGGESTIONS';
